import assert from 'node:assert/strict';
export async function networkCases(db,ctx) {
 const {publish,scalar,source,page,worker,token,reader,cid,cid2,hash,revision}=ctx;
 const extra='c'.repeat(24), other='d'.repeat(24), entity='80bfd686cfc3cbb697a4f15a';
 const terms=[{concept_id:cid,matched_label:'prostate cancer',vocabulary:'MeSH',year:'2026',checksum:'a'.repeat(64),status:'exact',entity_id:entity,label:'Prostate Cancer',category:'condition',descriptor_ids:['D011471'],concept_ui:'M0017834'}];
 const batch=items=>({id:cid,version:'corpus-v1',items});
 const get=(f={})=>scalar('SELECT public.knowledge_network($1) v',[f]);
 await assert.rejects(()=>get(),{code:'42501'});
 await assert.rejects(()=>scalar('SELECT public.publish_knowledge($1,$2,$3,$4,$5) v',[worker,'bad','terms',revision,batch(terms)]),{code:'42501'});
 await assert.rejects(()=>publish('terms',batch([{...terms[0],matched_label:'invented label'}])));
 await assert.rejects(()=>publish('terms',batch([{...terms[0],entity_id:cid}])));
 await assert.rejects(()=>publish('terms',batch([{...terms[0],quote:'raw text'}])));
 await publish('source',{...source,concepts:[...source.concepts,{...source.concepts[0],id:extra,label:'Cancer of Prostate',kind:'method'},{...source.concepts[0],id:other,label:'Unknown tissue',kind:'method'}]},'c'.repeat(64));
 await publish('page',page);
 await publish('terms',batch([...terms,{...terms[0],concept_id:extra,matched_label:'Cancer of Prostate'}]));
 await db.exec('RESET ROLE');await db.query("SELECT set_config('request.jwt.claim.sub',$1,false)",[reader]);await db.exec('SET ROLE authenticated');
 let d=await get();
 assert.equal(d.indexed_documents,1);assert.equal(d.nodes.length,3);
 assert.equal(d.nodes.find(n=>n.id===entity).document_count,1,'Same-paper aliases must not inflate counts');
 assert.equal(d.nodes.find(n=>n.id===other).kind,'unclassified','Model method label must not become authority');
 assert.equal(d.edges.length,3);assert(d.edges.every(e=>e.weight===1&&Number(e.jaccard)===1));
 assert.equal(d.coverage.resolved,1);
 assert.equal((await get({focus:extra})).focus,entity,'Legacy links resolve to canonical identity');
 assert.equal((await get({focus:entity})).notes.length,1);
 assert.equal((await get({min_shared:2})).edges.length,0);
 assert.equal((await get({focus:entity,peer:other})).selected_documents,1);
 assert.equal((await get({from:2025})).nodes.length,0);
 assert.equal((await get({q:'Cancer of Prostate'})).matched_documents,1);
 await assert.rejects(()=>get({unexpected:true}));await assert.rejects(()=>get({min_shared:0}));
 await assert.rejects(()=>get({limit:101}));await assert.rejects(()=>get({peer:other}));
 let c=await get({relation:'citations'});assert.equal(c.coverage.metadata_papers,0);assert.equal(c.edges.length,0);
 const bib={version:'corpus-v1',pmid:'12345',title:'Original',content_hash:hash,source:'PubMed',fetched_at:new Date().toISOString(),references:[{source_id:'ref1',pmid:'12346',doi:null}]};
 await assert.rejects(()=>publish('bibliography',{...bib,content_text:'raw'}));
 await assert.rejects(()=>publish('bibliography',{...bib,content_hash:'c'.repeat(64)}));
 await assert.rejects(()=>publish('bibliography',{...bib,references:[{source_id:'x',pmid:null,doi:null}]}));
 await publish('bibliography',bib);await publish('bibliography',bib);
 c=await get({relation:'citations'});assert.equal(c.coverage.metadata_papers,1);assert.equal(c.coverage.reference_identifiers,1);assert.equal(c.edges.length,0);
 await db.exec(`RESET ROLE;INSERT INTO public.papers(id,pmid,title,pub_date,fulltext_available) VALUES(992,'12346','Second','2024-02-01',true);
 INSERT INTO app_private.local_fulltext_sources(paper_id,worker_id,title,content_hash,summary_source_hash,characters,section_count) VALUES(992,'${worker}','Second','${hash}','${hash}',10000,3);SET ROLE authenticated;`);
 await publish('source',{...source,pmid:'12346',title:'Second',concepts:[source.concepts[0]]});
 d=await get();assert.equal(d.nodes.find(n=>n.id===entity).document_count,2);
 const edge=d.edges.find(e=>[e.source,e.target].includes(entity));assert.equal(Number(edge.jaccard),.5);
 c=await get({relation:'citations'});assert.deepEqual(c.edges,[{source:'12345',target:'12346',weight:1}]);
 assert.equal((await get({relation:'citations',focus:'12345',peer:'12346'})).selected_documents,2);
 await db.exec('RESET ROLE;DELETE FROM public.papers WHERE id=992;SET ROLE authenticated');
 await assert.rejects(()=>db.query('SELECT * FROM app_private.knowledge_term_resolutions'),{code:'42501'});
 await assert.rejects(()=>db.query('SELECT app_private.publish_knowledge_original($1,$2,$3,$4,$5)',[worker,token,'source',revision,source]),{code:'42501'});
 await db.exec(`RESET ROLE;UPDATE public.papers SET integrity_status='retracted' WHERE id=1;SET ROLE authenticated`);
 assert.equal((await get()).indexed_documents,0);
 await db.exec(`RESET ROLE;UPDATE public.papers SET integrity_status='current' WHERE id=1;SET ROLE anon`);
 await publish('source',source);await publish('page',page);
 console.log('Network DB passed: exact identities, distinct-paper counts, filters, citations, source binding, metadata-only publication and access controls.');
}
