import assert from 'node:assert/strict';
import {readFile,readdir} from 'node:fs/promises';
import {PGlite} from '../frontend/node_modules/@electric-sql/pglite/dist/index.js';
import {createHash} from 'node:crypto';
const db=new PGlite();
const a='00000000-0000-0000-0000-000000000001',b='00000000-0000-0000-0000-000000000002',c='00000000-0000-0000-0000-000000000003';
async function user(id){await db.exec('RESET ROLE');await db.query("SELECT set_config('request.jwt.claim.sub',$1,false)",[id]);await db.exec('SET ROLE authenticated')}
try{
 await db.exec(`CREATE ROLE anon;CREATE ROLE authenticated;CREATE ROLE service_role BYPASSRLS;CREATE SCHEMA auth;
 CREATE TABLE auth.users(id uuid PRIMARY KEY,email text,email_confirmed_at timestamptz,raw_user_meta_data jsonb);
 CREATE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql AS $$SELECT nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
 GRANT USAGE ON SCHEMA auth,public TO authenticated,anon;`);
 for(const file of (await readdir(new URL('../supabase/migrations/',import.meta.url))).filter(f=>f.endsWith('.sql')).sort()){
  await db.exec((await readFile(new URL('../supabase/migrations/'+file,import.meta.url),'utf8')).replace(/^\uFEFF/,''));
  console.log('applied '+file);
 }
 await db.exec(`GRANT SELECT,INSERT,UPDATE,DELETE ON public.collections,public.collection_papers,public.papers,public.profiles,public.feedbacks TO authenticated;
 GRANT USAGE,SELECT ON ALL SEQUENCES IN SCHEMA public TO authenticated;
 INSERT INTO auth.users VALUES('${a}','crazyslime@gmail.com',now(),'{}'),('${b}','reader@example.test',now(),'{}'),('${c}','outsider@example.test',now(),'{}');
 INSERT INTO public.papers(id,pmid,title,doi,pub_date,abstract) VALUES(1,'10001','Prostate cancer follow up','10.1000/test','2026-01-01','Prospective cohort'),(2,'10002','Bladder cancer','10.1000/other','2025-01-01','Retrospective cohort');`);
 await user(a);
 const search=await db.query("SELECT public.search_papers('10001') result");assert.equal(search.rows[0].result.items.length,1);
 assert.equal((await db.query("SELECT public.search_papers('https://doi.org/10.1000/test') r")).rows[0].r.items[0].pmid,'10001');
 assert.equal((await db.query("SELECT public.reader_paper('10001') r")).rows[0].r.paper.title,'Prostate cancer follow up');
 await db.query("SELECT public.update_reader_state(1,'{\"saved\":true,\"note\":\"private\"}')");
 await db.query("SELECT public.update_reader_state(1,'{\"reading_state\":\"read\"}')");
 assert.equal((await db.query('SELECT note FROM public.reader_states')).rows[0].note,'private');
 await db.query("SELECT public.reader_opinion(1,'dislike')");assert.equal((await db.query('SELECT saved FROM public.reader_states')).rows[0].saved,true);
 await db.query("INSERT INTO public.collections(id,user_id,name,keywords) VALUES(10,$1,'Project',ARRAY['prostate'])",[a]);
 await db.query('INSERT INTO public.collection_papers VALUES(10,1,now())');
 await db.query("SELECT public.project_members(10,'reader@example.test','reader')");
 await user(b);assert.equal((await db.query('SELECT * FROM public.reader_states')).rows.length,0);
 assert.equal((await db.query('SELECT * FROM public.collections')).rows.length,0);
 assert.equal((await db.query('SELECT public.project_invitations() r')).rows[0].r.length,1);
 await db.query('SELECT public.project_invitations(10)');
 assert.equal((await db.query('SELECT public.project_papers(10) r')).rows[0].r.items.length,1);
 await assert.rejects(db.query('INSERT INTO public.collection_papers VALUES(10,2,now())'));
 await user(a);await db.query("SELECT public.project_members(10,'reader@example.test','editor')");
 await user(b);await db.query('INSERT INTO public.collection_papers VALUES(10,2,now())');
 await db.query("INSERT INTO public.project_notes(collection_id,paper_id,note,updated_by) VALUES(10,2,'Team note',$1)",[b]);
 await db.query('SELECT public.project_recommendations(10)');
 await assert.rejects(db.query("SELECT public.project_members(10,'outsider@example.test','editor')"));
 await user(c);assert.equal((await db.query('SELECT * FROM public.project_notes')).rows.length,0);await assert.rejects(db.query('SELECT public.project_papers(10)'));
 await user(a);await db.query('SELECT public.project_members(10,NULL,\'reader\',$1)',[b]);
 await user(b);assert.equal((await db.query('SELECT * FROM public.project_notes')).rows.length,0);
 await db.query("INSERT INTO public.summary_issues(user_id,paper_id,category,message) VALUES($1,1,'summary','Check value')",[b]);
 await assert.rejects(db.query('SELECT public.admin_summary_issues()'));
 await db.query("INSERT INTO public.saved_searches(user_id,name,query) VALUES($1,'Topic','prostate')",[b]);
 await db.query('SELECT public.search_notifications()');await db.query('SELECT public.reader_daily()');
 await user(a);assert.equal((await db.query('SELECT public.admin_summary_issues() r')).rows[0].r.length,1);
 await db.exec('RESET ROLE');
 const sha=x=>createHash('sha256').update(x).digest('hex'),token='synthetic-token-'.repeat(4),worker='00000000-0000-0000-0000-000000000009';
 await db.query('INSERT INTO app_private.institution_workers(id,name,token_hash) VALUES($1,$2,$3)',[worker,'fixture',sha(token)]);
 const body='Synthetic source for validated summary publication. '.repeat(60),hash=sha('fulltext\nProstate cancer follow up\n'+body);
 const details=Object.fromEntries(['intervention','comparator','follow_up','outcome','limitations'].map(k=>[k,'Not reported']));
 const structured=Object.fromEntries(['study_design','sample_size','key_finding','population'].map(k=>[k,'Not reported']));
 const source={content_hash:sha(body),characters:body.length,section_count:2,source_url:'https://example.test/article'};
 const derived={summary_ko:'연구 설계를 확인했다.\n결과를 확인했다.\n해석에 한계가 있다.',structured_data:structured,qa_data:[{q:'한계는?',a:'Not reported'}],clinical_relevance:3,summary_model:'spark/fixture.evidence-v1',summary_source_hash:hash,research_details:details,
 evidence:{version:1,content_hash:sha(body),claims:{summary_1:['p-0000000'],summary_2:['p-0000000'],summary_3:['p-0000000'],...Object.fromEntries([...Object.keys(details),...Object.keys(structured),'qa_1'].map(k=>[k,[]]))}}};
 const publish=(summary=derived)=>db.query('SELECT public.publish_institution_summary($1,$2,$3,$4,$5,$6,$7)',[worker,token,'10001','10.1000/test','Prostate cancer follow up',JSON.stringify(source),JSON.stringify(summary)]);
 await db.exec('SET ROLE anon');await publish();
 await assert.rejects(publish({...derived,evidence:{...derived.evidence,claims:{summary_1:[body],summary_2:['p-0000000'],summary_3:['p-0000000']}}}));
 await assert.rejects(publish({...derived,content_text:body}));
 await db.exec('RESET ROLE');
 assert.deepEqual((await db.query('SELECT evidence FROM public.papers WHERE id=1')).rows[0].evidence,derived.evidence);
 await db.exec(`UPDATE public.papers SET integrity_status='corrected',related_notices='[{"pmid":"20001","relation":"ErratumIn"}]' WHERE id=1`);
 await publish();assert.equal((await db.query('SELECT summary_review_required FROM public.papers WHERE id=1')).rows[0].summary_review_required,true);
 await user(b);await assert.rejects(db.query('SELECT public.admin_integrity_review()'));
 await db.query(`UPDATE public.saved_searches SET filters='{"year":"invalid","until":"-12"}'`);await db.query('SELECT public.search_notifications()');
 await user(a);await assert.rejects(db.query('SELECT public.admin_integrity_review(1,$1,$2)',['stale','Reviewed updated original and notice.']));
 await db.query('SELECT public.admin_integrity_review(1,$1,$2)',[hash,'Reviewed updated original and linked notice.']);
 await db.exec('RESET ROLE');assert.equal((await db.query('SELECT summary_review_required FROM public.papers WHERE id=1')).rows[0].summary_review_required,false);
 await db.exec(`INSERT INTO public.papers(id,pmid,title,pub_date,abstract) VALUES(3,'10003','Veterans Affairs and repair','2026-01-01','Available trials'),(4,'10004','AI-assisted diagnosis','2026-01-01','Artificial intelligence');UPDATE public.papers SET integrity_status='retracted' WHERE id=1;`);
 await user(a);assert.equal((await db.query("SELECT public.search_papers('AI') r")).rows[0].r.items[0].pmid,'10004');assert.equal((await db.query("SELECT public.search_papers('AI') r")).rows[0].r.total,1);
 assert.equal((await db.query('SELECT public.reader_daily() r')).rows[0].r.length,0);
 await assert.rejects(db.query('SELECT public.admin_integrity_review(1,$1,$2)',[hash,'Retraction must remain excluded.']));
 await db.exec("RESET ROLE;UPDATE public.papers SET title='Changed title' WHERE id=1");
 assert.deepEqual((await db.query('SELECT evidence FROM public.papers WHERE id=1')).rows[0].evidence,{});
 await db.exec("RESET ROLE;SET ROLE anon;SELECT set_config('request.jwt.claim.sub','',false)");
 await assert.rejects(db.query("SELECT public.search_papers('prostate')"));await db.query('SELECT public.preview_papers()');
 console.log('Reader searches, identity isolation, reader/editor sharing, revocation, reports, notifications passed');
} catch(e){console.error(e.message,e.where||'',e.query||'');process.exitCode=1} finally {await db.close()}
