import assert from 'node:assert/strict';
import {readFile,readdir} from 'node:fs/promises';
import {randomUUID} from 'node:crypto';
import {PGlite} from '../frontend/node_modules/@electric-sql/pglite/dist/index.js';
const db=new PGlite();
const owner='00000000-0000-0000-0000-000000000001', reader='00000000-0000-0000-0000-000000000002', outsider='00000000-0000-0000-0000-000000000003';
const user=async id=>{await db.exec('RESET ROLE');await db.query("SELECT set_config('request.jwt.claim.sub',$1,false)",[id]);await db.exec('SET ROLE authenticated');};
const rpc=async(name,args)=>{const es=Object.entries(args);return (await db.query(`SELECT public.${name}(${es.map(([k],i)=>`${k}=>$${i+1}`).join(',')}) r`,es.map(([,v])=>v&&typeof v==='object'&&!Array.isArray(v)?JSON.stringify(v):v))).rows[0].r;};
const migration=async f=>db.exec((await readFile(new URL('../supabase/migrations/'+f,import.meta.url),'utf8')).replace(/^\uFEFF/,''));
try {
 await db.exec(`CREATE ROLE anon; CREATE ROLE authenticated; CREATE ROLE service_role BYPASSRLS; CREATE SCHEMA auth;
 CREATE TABLE auth.users(id uuid PRIMARY KEY,email text,email_confirmed_at timestamptz,raw_user_meta_data jsonb);
 CREATE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql AS $$SELECT nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
 GRANT USAGE ON SCHEMA auth,public TO anon,authenticated;`);
 const files=(await readdir(new URL('../supabase/migrations/',import.meta.url))).filter(x=>x.endsWith('.sql')).sort();
 for(const file of files.filter(x=>x<'041'))await migration(file);
 await db.exec(`INSERT INTO auth.users VALUES('${owner}','owner@example.test',now(),'{}'),('${reader}','reader@example.test',now(),'{}'),('${outsider}','outsider@example.test',now(),'{}');
 INSERT INTO public.collections(id,user_id,name) VALUES(10,'${owner}','Project'),(11,'${outsider}','Private');
 INSERT INTO public.collection_members(collection_id,user_id,role,accepted) VALUES(10,'${reader}','reader',true);
 INSERT INTO public.papers(id,pmid,title,pub_date,abstract,authors) VALUES(1,'10001','Existing project paper','2025-01-01','Abstract one','["Author"]'),(2,'10002','New discovery paper','2025-01-02','Abstract two','[]'),(3,'10003','Unrelated private paper','2025-01-03','','[]');
 INSERT INTO public.collection_papers(collection_id,paper_id) VALUES(10,1),(11,3);
 INSERT INTO public.project_notes(collection_id,paper_id,note,updated_by) VALUES(10,1,'Preserve this note','${owner}');
 INSERT INTO public.reader_states(user_id,paper_id,saved) VALUES('${owner}',2,true);`);
 for(const file of files.filter(x=>x>='041'))await migration(file);
 await db.exec('GRANT SELECT ON public.papers,public.collections,public.collection_papers TO authenticated; GRANT INSERT ON public.collection_papers TO authenticated');
 await user(owner);
 let docs=await rpc('project_documents',{p_id:10});assert.equal(docs.total,1);assert.equal(docs.items[0].note,'Preserve this note');assert.equal(docs.items[0].ta_decision,'pending');
 let w=await rpc('review_workspace',{p_project:10});assert.equal(w.counts.records,1);assert.equal(w.counts.included,0);
 const searches=(await rpc('review_list',{p_project:10,p_section:'searches'})).items;assert.equal(searches.length,1);assert.equal(searches[0].status,'partial');assert.equal(searches[0].reported_hits,null);
 let context=await rpc('workspace_paper_context',{p_papers:[1,2,3]});assert.equal(context.find(x=>x.paper_id===1).saved,false);assert.equal(context.find(x=>x.paper_id===2).saved,true);assert.equal(context.find(x=>x.paper_id===3).projects.length,0);
 const sid=randomUUID();await rpc('review_save_search',{p_project:10,p_id:sid,p_expected_revision:0,p_payload:{source:'Discovery',query:'original strategy',searched_at:new Date().toISOString(),status:'partial'}});
 const items=[{source_record_id:'PMID:10002',paper_id:2,bibliography:{title:'New discovery paper',pmid:'10002',authors:[]}}];
 const importArgs={p_project:10,p_search:sid,p_items:JSON.stringify(items)};
 assert.equal((await rpc('review_import_records',importArgs)).imported,1);
 assert.equal((await rpc('review_import_records',importArgs)).imported,0);
 assert.equal((await db.query('SELECT * FROM public.collection_papers WHERE collection_id=10')).rows.length,2);
 assert.equal((await db.query('SELECT * FROM public.research_reference_entries WHERE collection_id=10')).rows.length,2);
 docs=await rpc('project_documents',{p_id:10});assert.equal(docs.total,2);
 w=await rpc('review_workspace',{p_project:10});assert.equal(w.counts.records,2);assert.equal(w.counts.reports,2);
 const report=docs.items.find(x=>x.id===2);
 await rpc('review_save_report',{p_project:10,p_id:report.report_id,p_expected_revision:1,p_payload:{ta_decision:'exclude',ft_decision:'pending',acquisition:'unknown',exclusion_reason:'Wrong population',source:{},note:'Decision stays'}});
 await db.query('INSERT INTO public.collection_papers(collection_id,paper_id) VALUES(10,2) ON CONFLICT DO NOTHING');
 context=await rpc('workspace_paper_context',{p_papers:[2]});assert.equal(context[0].projects[0].ta_decision,'exclude');
 // External references appear in the SAME document list without a fabricated catalog identity.
 await rpc('review_import_records',{p_project:10,p_search:sid,p_items:JSON.stringify([{source_record_id:'EXT:1',bibliography:{title:'External historical trial',authors:[],year:'1990',doi:'10.1000/external'}}])});
 docs=await rpc('project_documents',{p_id:10,p_query:'External'});assert.equal(docs.total,1);assert.equal(docs.items[0].external,true);assert.equal(docs.items[0].id,undefined);
 assert.equal((await db.query('SELECT * FROM public.research_reference_entries WHERE collection_id=10 AND paper_id IS NULL')).rows.length,1);
 assert.equal((await rpc('project_documents',{p_id:10,p_query:'Preserve this note'})).total,1);
 // Later catalog identification must reuse the external report and durable reference.
 await db.exec('RESET ROLE');
 await db.exec("INSERT INTO public.papers(id,pmid,title,pub_date,doi) VALUES(4,'10004','External historical trial','2001-01-01','10.1000/external')");
 await user(owner);
 const external=docs.items[0];
 await rpc('review_import_records',{p_project:10,p_search:sid,p_items:JSON.stringify([{source_record_id:'PMID:10004',paper_id:4,bibliography:{title:'External historical trial',pmid:'10004',doi:'10.1000/external',authors:[]}}])});
 docs=await rpc('project_documents',{p_id:10,p_query:'External'});assert.equal(docs.total,1);assert.equal(docs.items[0].report_id,external.report_id);assert.equal(docs.items[0].id,4);
 assert.equal((await db.query('SELECT * FROM public.research_reference_entries WHERE collection_id=10 AND review_report_id=$1',[external.report_id])).rows.length,1);
 await user(reader);assert.equal((await rpc('project_documents',{p_id:10})).can_edit,false);assert.equal((await rpc('workspace_paper_context',{p_papers:[1]}))[0].projects.length,1);
 await assert.rejects(db.query('INSERT INTO public.collection_papers(collection_id,paper_id) VALUES(10,3)'),{code:'42501'});
 await user(outsider);await assert.rejects(rpc('project_documents',{p_id:10}),{code:'42501'});assert.equal((await rpc('workspace_paper_context',{p_papers:[1]}))[0].projects.length,0);
 await assert.rejects(rpc('workspace_paper_context',{p_papers:Array(101).fill(1)}),{code:'22023'});
 await db.exec('RESET ROLE; SET ROLE anon');await assert.rejects(rpc('workspace_paper_context',{p_papers:[1]}),{code:'42501'});
 console.log('Connected research: legacy reconciliation, provenance, bidirectional additions, idempotence, preserved decisions/notes, external references, private saves and role isolation passed.');
} finally {await db.close();}
