import assert from 'node:assert/strict';
import {readFile,readdir} from 'node:fs/promises';
import {randomUUID,createHash} from 'node:crypto';
import {PGlite} from '../frontend/node_modules/@electric-sql/pglite/dist/index.js';
const db=new PGlite();
const owner='00000000-0000-0000-0000-000000000001', outsider='00000000-0000-0000-0000-000000000002';
const user=async id=>{await db.exec('RESET ROLE');await db.query("SELECT set_config('request.jwt.claim.sub',$1,false)",[id]);await db.exec('SET ROLE authenticated');};
const rpc=async(name,args)=>{const es=Object.entries(args);return (await db.query(`SELECT public.${name}(${es.map(([k],i)=>`${k}=>$${i+1}`).join(',')}) r`,es.map(([,v])=>v&&typeof v==='object'?JSON.stringify(v):v))).rows[0].r;};
try {
 await db.exec(`CREATE ROLE anon; CREATE ROLE authenticated; CREATE ROLE service_role BYPASSRLS; CREATE SCHEMA auth;
 CREATE TABLE auth.users(id uuid PRIMARY KEY,email text,email_confirmed_at timestamptz,raw_user_meta_data jsonb);
 CREATE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql AS $$SELECT nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
 GRANT USAGE ON SCHEMA auth,public TO anon,authenticated;`);
 for(const file of (await readdir(new URL('../supabase/migrations/',import.meta.url))).filter(x=>x.endsWith('.sql')).sort()) {
  try{await db.exec((await readFile(new URL('../supabase/migrations/'+file,import.meta.url),'utf8')).replace(/^\uFEFF/,''));}
  catch(e){const sql=await readFile(new URL('../supabase/migrations/'+file,import.meta.url),'utf8');console.error('Migration failed:',file,'at',e.position,sql.slice(Number(e.position)-150,Number(e.position)+100));throw e;}
 }
 await db.exec(`INSERT INTO auth.users VALUES('${owner}','review-owner@example.test',now(),'{}'),('${outsider}','review-other@example.test',now(),'{}');
 INSERT INTO public.collections(id,user_id,name) VALUES(10,'${owner}','Review'),(11,'${outsider}','Other');
 INSERT INTO public.papers(id,pmid,title,pub_date,abstract,authors) VALUES(1,'10001','Catalog report','2026-01-01','Canonical abstract retained','["Catalog Author"]');`);
 await user(owner);
 const protocol={question:'Does treatment help?',type:'intervention',population:'Adults',outcomes:'Mortality',eligibility:'Parallel randomized trials',search_plan:'PubMed and registries',analysis_plan:'RR with REML',status:'locked'};
 const p=await rpc('review_save_protocol',{p_project:10,p_expected_version:0,p_payload:protocol});assert.equal(p.version,1);
 await assert.rejects(rpc('review_save_protocol',{p_project:10,p_expected_version:0,p_payload:protocol}),{code:'40001'});
 await assert.rejects(rpc('review_save_protocol',{p_project:10,p_expected_version:1,p_payload:protocol}),{code:'22023'});
 await assert.rejects(rpc('review_save_protocol',{p_project:10,p_expected_version:1,p_payload:{...protocol,api_key:'synthetic-never-persist'}}),{code:'22023'});
 const search=randomUUID();
 await rpc('review_save_search',{p_project:10,p_id:search,p_expected_revision:0,p_payload:{source:'RIS import',query:'Recorded strategy',searched_at:'2026-09-23T00:00:00Z',status:'complete',reported_hits:2}});
 const a={source_record_id:'1',bibliography:{title:'Independent randomized trial',authors:['Author A'],year:'1998',doi:'10.1000/example'}};
 const b={source_record_id:'2',bibliography:{title:'Catalog report',authors:[],pmid:'10001',year:'2026'},paper_id:1};
 assert.equal((await rpc('review_import_records',{p_project:10,p_search:search,p_items:[a,b]})).imported,2);
 assert.equal((await rpc('review_import_records',{p_project:10,p_search:search,p_items:[a,b]})).imported,0);
 let reports=(await rpc('review_list',{p_project:10,p_section:'reports'})).items;
 assert.equal(reports.find(x=>x.paper_id===1).bibliography.abstract,'Canonical abstract retained');
 assert.deepEqual(reports.find(x=>x.paper_id===1).bibliography.authors,['Catalog Author']);
 let report=reports.find(x=>x.bibliography.doi);
 const screen={ta_decision:'include',ft_decision:'include',acquisition:'acquired',exclusion_reason:'',source:{hash:'a'.repeat(64),locator:'Table 2',type:'fulltext'},note:''};
 report=await rpc('review_save_report',{p_project:10,p_id:report.id,p_expected_revision:1,p_payload:screen});
 await assert.rejects(rpc('review_save_report',{p_project:10,p_id:report.id,p_expected_revision:1,p_payload:screen}),{code:'40001'});
 await assert.rejects(rpc('review_save_report',{p_project:10,p_id:report.id,p_expected_revision:2,p_payload:{...screen,ft_decision:'exclude'}}),{code:'22023'});
 const study=randomUUID();
 await rpc('review_save_study',{p_project:10,p_id:study,p_expected_revision:0,p_payload:{label:'Trial A',design:'parallel_RCT',report_ids:[report.id],link_reason:'Same trial registry and population'}});
 const obs=randomUUID();
 const payload={study_id:study,report_id:report.id,kind:'binary',context:{cohort:'primary',independence_group:'Trial A',outcome:'Mortality',timepoint:'12 months',comparison:'Treatment vs control',unit:'participant',direction:'lower_better',analysis_population:'ITT',adjustment:'unadjusted',value_origin:'reported'},
  values:{events_t:12,n_t:100,events_c:20,n_c:100},evidence:{source_hash:'a'.repeat(64),source_type:'fulltext',source_checked:true,report_revision:report.revision,locator:'Table 2 / mortality / both arms'},status:'confirmed'};
 const saved=await rpc('review_save_observation',{p_project:10,p_id:obs,p_expected_revision:0,p_payload:payload});assert.equal(saved.confirmed_by,owner);
 await assert.rejects(rpc('review_save_observation',{p_project:10,p_id:randomUUID(),p_expected_revision:0,p_payload:{...payload,values:{...payload.values,events_t:101}}}),{code:'22023'});
 await assert.rejects(rpc('review_save_observation',{p_project:10,p_id:randomUUID(),p_expected_revision:0,p_payload:{...payload,evidence:{...payload.evidence,source_type:'summary'}}}),{code:'22023'});
 await assert.rejects(rpc('review_save_observation',{p_project:10,p_id:randomUUID(),p_expected_revision:0,p_payload:{...payload,confirmed_by:outsider}}),{code:'22023'});
 const summary=await rpc('review_workspace',{p_project:10});assert.equal(summary.counts.records,2);assert.equal(summary.counts.studies,1);assert.equal(summary.counts.confirmed,1);
 const incomplete={...payload,status:'draft',values:{...payload.values,events_t:null,missing:{events_t:'Not reported'}}};
 const draftId=randomUUID();
 assert.equal((await rpc('review_save_observation',{p_project:10,p_id:draftId,p_expected_revision:0,p_payload:incomplete})).values.events_t,null);
 await assert.rejects(rpc('review_save_observation',{p_project:10,p_id:draftId,p_expected_revision:1,p_payload:{...incomplete,status:'confirmed'}}),{code:'22023'});
 await assert.rejects(rpc('review_save_observation',{p_project:10,p_id:draftId,p_expected_revision:1,p_payload:{...incomplete,values:{...incomplete.values,missing:{}}}}),{code:'22023'});
 const supplement=await rpc('review_save_observation',{p_project:10,p_id:randomUUID(),p_expected_revision:0,p_payload:{...payload,evidence:{...payload.evidence,source_type:'supplement',source_hash:'b'.repeat(64)}}});
 assert.equal(supplement.evidence.source_hash,'b'.repeat(64));
 const config={profile:'pairwise-binary-v1',measure:'RR',outcome:'Mortality',timepoint:'12 months',comparison:'Treatment vs control',unit:'participant',analysis_population:'ITT',adjustment:'unadjusted',analysis_intent:'prespecified'};
 const runId=randomUUID(),runArgs={p_project:10,p_run_id:runId,p_protocol_version:1,p_rows:[{id:obs,revision:saved.revision}],p_config:config};
 const queued=await rpc('review_start_analysis',runArgs);assert.equal(queued.status,'queued');
 assert.deepEqual(await rpc('review_start_analysis',runArgs),queued);
 await assert.rejects(rpc('review_start_analysis',{...runArgs,p_run_id:randomUUID(),p_rows:[{id:obs,revision:99}]}),{code:'40001'});
 await assert.rejects(rpc('review_start_analysis',{...runArgs,p_run_id:randomUUID(),p_rows:[{id:obs,revision:1},{id:obs,revision:1}]}),{code:'22023'});
 await assert.rejects(rpc('review_start_analysis',{...runArgs,p_run_id:randomUUID(),p_config:{...config,timepoint:'24 months'}}),{code:'22023'});
 const worker=randomUUID(),token='fixture-review-worker-token-not-real-'.repeat(2);
 await db.exec('RESET ROLE');
 await db.query('INSERT INTO app_private.institution_workers(id,name,token_hash) VALUES($1,$2,$3)',[worker,'Review fixture',createHash('sha256').update(token).digest('hex')]);
 await db.exec('SET ROLE anon');
 await assert.rejects(rpc('claim_review_analysis',{p_worker_id:worker,p_token:'invalid'}));
 const job=await rpc('claim_review_analysis',{p_worker_id:worker,p_token:token});
 assert.equal(job.id,runId);assert.equal(job.input.screening.counts.records,2);assert.equal(job.input.search_history.length,1);assert.equal(job.input.review_status,'not_peer_reviewed');
 assert.equal(await rpc('claim_review_analysis',{p_worker_id:worker,p_token:token}),null);
 const result={schema_version:1,status:'succeeded',input_hash:job.input_hash,engine:{name:'uro-review-python',code_sha256:'c'.repeat(64)},config,rows:[{id:obs}],pooled:null};
 const finish={p_worker_id:worker,p_token:token,p_id:job.id,p_lease_token:job.lease_token,p_input_hash:job.input_hash,p_result:result};
 assert.equal(await rpc('finish_review_analysis',{...finish,p_lease_token:randomUUID()}),false);
 await assert.rejects(rpc('finish_review_analysis',{...finish,p_result:{...result,config:{...config,measure:'OR'}}}),{code:'22023'});
 await assert.rejects(rpc('finish_review_analysis',{...finish,p_result:{status:'succeeded',input_hash:job.input_hash}}),{code:'22023'});
 assert.equal(await rpc('finish_review_analysis',finish),true);
 assert.equal(await rpc('finish_review_analysis',finish),false);
 await user(owner);
 const completed=await rpc('review_analysis',{p_project:10,p_id:runId});assert.equal(completed.status,'succeeded');assert.equal(completed.lease_token,undefined);
 await assert.rejects(db.query('SELECT lease_token FROM public.review_analysis_runs'),{code:'42501'});
 const cancelledId=randomUUID();await rpc('review_start_analysis',{...runArgs,p_run_id:cancelledId});
 await rpc('review_analysis',{p_project:10,p_id:cancelledId,p_cancel:true});
 await db.exec('RESET ROLE; SET ROLE anon');assert.equal(await rpc('claim_review_analysis',{p_worker_id:worker,p_token:token}),null);await user(owner);
 await rpc('review_save_report',{p_project:10,p_id:report.id,p_expected_revision:2,p_payload:{...screen,note:'Source checked again'}});
 assert.equal((await rpc('review_list',{p_project:10,p_section:'observations'})).items.find(x=>x.id===obs).status,'needs_revalidation');
 assert.equal((await rpc('review_analysis',{p_project:10,p_id:runId})).input_manifest.observations[0].report_revision,2);
 assert.equal((await rpc('review_analysis',{p_project:10,p_id:runId})).stale_input,true);
 await assert.rejects(rpc('review_start_analysis',{...runArgs,p_run_id:randomUUID()}),{code:'40001'});
 await assert.rejects(db.query("UPDATE public.review_observations SET status='confirmed' WHERE id=$1",[obs]),{code:'42501'});
 await user(outsider);
 for(const [name,args] of [['review_workspace',{p_project:10}],['review_list',{p_project:10,p_section:'reports'}],['review_save_protocol',{p_project:10,p_expected_version:1,p_payload:protocol}]]) await assert.rejects(rpc(name,args),{code:'42501'});
 assert.equal((await db.query('SELECT * FROM public.review_observations')).rows.length,0);
 console.log('Systematic reviews: authorization, immutable protocol, imports, provenance, screening, study linkage, typed values, source invalidation and private reads passed.');
} catch(e){console.error({code:e.code,message:e.message,detail:e.detail,where:e.where,query:e.internalQuery});process.exitCode=1;} finally {await db.close();}
