import assert from 'node:assert/strict';
import {readFile,readdir} from 'node:fs/promises';
import {PGlite} from '../frontend/node_modules/@electric-sql/pglite/dist/index.js';
const db=new PGlite();
const reader='00000000-0000-0000-0000-000000000002',worker='10000000-0000-0000-0000-000000000001',token='x'.repeat(48);
const cid='a'.repeat(24),cid2='b'.repeat(24),hash='a'.repeat(64),revision='b'.repeat(64);
const scalar=async(q,p=[]) => (await db.query(q,p)).rows[0].v;
const publish=(kind,payload,rev=revision)=>scalar('SELECT public.publish_knowledge($1,$2,$3,$4,$5) v',[worker,token,kind,rev,payload]);
const concept={id:cid,label:'prostate cancer',label_ko:'전립선암',kind:'condition',aliases:[]};
const source={pmid:'12345',title:'Original',content_hash:hash,version:'corpus-v1',concepts:[concept,{...concept,id:cid2,label:'active surveillance',label_ko:'적극적 감시',kind:'intervention'}]};
const page={id:cid,version:'corpus-v1-en',paragraphs:[{text:'This is a synthetic knowledge sentence for testing.',sources:[{pmid:'12345',content_hash:hash,locations:['p-0000000']}]}]};
try {
 await db.exec(`CREATE ROLE anon;CREATE ROLE authenticated;CREATE ROLE service_role BYPASSRLS;CREATE SCHEMA auth;
 CREATE TABLE auth.users(id uuid PRIMARY KEY,email text,email_confirmed_at timestamptz,raw_user_meta_data jsonb);
 CREATE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql AS $$SELECT nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
 GRANT USAGE ON SCHEMA auth,public TO authenticated,anon;`);
 const root=new URL('../supabase/migrations/',import.meta.url);
 for(const f of (await readdir(root)).filter(x=>x.endsWith('.sql')).sort()) await db.exec((await readFile(new URL(f,root),'utf8')).replace(/^\uFEFF/,''));
 await db.exec(`INSERT INTO auth.users VALUES('${reader}','reader@example.test',now(),'{}');
 INSERT INTO public.papers(id,pmid,title,pub_date,fulltext_available) VALUES(1,'12345','Original','2024-01-01',true);
 INSERT INTO app_private.institution_workers(id,name,token_hash) VALUES('${worker}','Fixture',encode(sha256(convert_to('${token}','UTF8')),'hex'));
 INSERT INTO app_private.local_fulltext_sources(paper_id,worker_id,title,content_hash,summary_source_hash,characters,section_count)
 VALUES(1,'${worker}','Original','${hash}','${hash}',10000,3);`);
 await assert.rejects(()=>db.query('SELECT public.publish_knowledge($1,$2,$3,$4,$5)',[worker,'bad','source',revision,source]),{code:'42501'});
 await db.exec('SET ROLE anon');
 await assert.rejects(()=>scalar('SELECT public.knowledge_search() v'),{code:'42501'});
 await assert.rejects(()=>publish('source',{...source,content_text:'raw original'}));
 assert.deepEqual(await publish('source',source),{id:'12345',revision});
 await publish('source',source);await publish('page',page);
 await assert.rejects(()=>publish('page',{...page,version:'corpus-v1'}));
 await assert.rejects(()=>publish('page',{...page,paragraphs:[{...page.paragraphs[0],text:'한국어 문장은 게시할 수 없습니다.'}]}));
 await db.exec("RESET ROLE;UPDATE app_private.knowledge_pages SET version='corpus-v1',stale=false");
 await db.exec(await readFile(new URL('20261008024637_knowledge_english.sql',root),'utf8'));
 await db.query("SELECT set_config('request.jwt.claim.sub',$1,false)",[reader]);await db.exec('SET ROLE authenticated');
 assert.equal((await scalar('SELECT public.knowledge_page($1) v',[cid])).wiki.status,'updating');
 assert.deepEqual((await scalar('SELECT public.knowledge_page($1) v',[cid])).wiki.paragraphs,[]);
 await publish('page',page);
 await publish('network',{version:'corpus-v1',scope_concepts:2,source_documents:1,groups:[{id:cid,label:'전립선암',concepts:[cid,cid2]}]});
 await db.exec('RESET ROLE');await db.query("SELECT set_config('request.jwt.claim.sub',$1,false)",[reader]);await db.exec('SET ROLE authenticated');
 const search=await scalar('SELECT public.knowledge_search() v');assert.equal(search.indexed_documents,1);assert.equal(search.items[0].document_count,1);
 assert.equal((await scalar('SELECT public.knowledge_search($1) v',['전립선'])).items.length,1);
 const detail=await scalar('SELECT public.knowledge_page($1) v',[cid]);assert.equal(detail.wiki.status,'ready');assert.equal(detail.papers.length,1);assert.equal(detail.neighbors[0].shared_papers,1);
 assert.equal((await scalar('SELECT public.knowledge_graph() v')).edges[0].weight,1);
 assert.equal((await scalar('SELECT public.knowledge_graph() v')).groups[0].concepts.length,2);
 // Scientific records are independently authenticated, typed and original-bound.
 const bib={source:'PubMed',fetched_at:'2026-10-08T03:00:00Z',pmid:'12345',title:'Original',doi:null,pmcid:null,journal:'Urology',volume:'1',issue:'2',pages:'1-3',authors:['Fixture Author'],issns:[],dates:[{kind:'journal',date:'2024',precision:'year',raw:'2024'}],publication_types:['Journal Article'],mesh:[],registry_ids:['NCT12345678'],references:[{source_id:'ref1',pmid:'12346',doi:null}],related_articles:[]};
 const fact={id:'f'.repeat(24),field:'sample_size',value:'195 men',locations:['p-0000000']};
 const numerical={id:'e'.repeat(24),measure:'HR',estimate:'0.70',ci_low:'0.50',ci_high:'0.90',ci_level:'95',outcome:'recurrence',population:'195 men',comparison:null,timepoint:'12 months',unit:null,adjustment:'adjusted',locations:['p-0000000']};
 const science={version:'scientific-v1',pmid:'12345',title:'Original',content_hash:hash,bibliography:bib,facts:[fact],results:[numerical],terminology:[],registry_mentions:[],provenance:{model:'Fixture',recipe:'scientific-v1',extracted_at:'2026-10-08T03:00:00Z',validation:'source_checked',review_status:'unreviewed',chunks:2,rejected_candidates:1},coverage:{facts_total:1,results_total:1,facts_published:1,results_published:1}};
 const publishScience=(value= science,key=token)=>scalar('SELECT public.publish_scientific_knowledge($1,$2,$3,$4) v',[worker,key,revision,value]);
 await assert.rejects(()=>publishScience(science,'bad'),{code:'42501'});
 await assert.rejects(()=>publishScience({...science,content_text:'raw original'}));
 await assert.rejects(()=>publishScience({...science,facts:[{...fact,quote:'raw original'}]}));
 await assert.rejects(()=>publishScience({...science,results:[{...numerical,ci_low:'0.80'}]}));
 await assert.rejects(()=>publishScience({...science,results:[{...numerical,locations:['p-9999999']}]}));
 await assert.rejects(()=>publishScience({...science,provenance:{...science.provenance,review_status:'human_reviewed'}}));
 await publishScience();await publishScience();
 const scienceDetail=await scalar('SELECT public.knowledge_paper($1) v',['12345']);
 assert.equal(scienceDetail.science.results[0].estimate,'0.70');assert.equal(scienceDetail.science.bibliography.dates[0].date,'2024');
 assert.equal(scienceDetail.science.provenance.review_status,'unreviewed');
 await db.exec(`RESET ROLE; UPDATE public.papers SET journal='Urology',study_type='RCT' WHERE id=1;
 INSERT INTO public.papers(id,pmid,title,journal,pub_date,fulltext_available,study_type) VALUES(991,'12346','Another original','Other journal','2023-02-01',true,'Retrospective');
 INSERT INTO app_private.local_fulltext_sources(paper_id,worker_id,title,content_hash,summary_source_hash,characters,section_count) VALUES(991,'${worker}','Another original','${hash}','${hash}',10000,3);SET ROLE authenticated;`);
 await publish('source',{...source,pmid:'12346',title:'Another original'});
 await publishScience({...science,pmid:'12346',title:'Another original',bibliography:{...bib,pmid:'12346',title:'Another original',references:[],registry_ids:[]},registry_mentions:['NCT12345678']});
 const atlas=await scalar('SELECT public.knowledge_atlas() v');
 assert.equal(atlas.matched_documents,2);assert.equal(atlas.structured_documents,2);assert.deepEqual(atlas.years.map(y=>y.year),[2023,2024]);
 assert.equal(atlas.nodes[0].document_count,2);
 assert.equal((await scalar("SELECT public.knowledge_atlas(p_journal=>'Urology',p_from=>2024,p_to=>2024,p_design=>'RCT') v")).matched_documents,1);
 assert.equal((await scalar("SELECT public.knowledge_atlas(p_query=>'no-such-paper') v")).papers.length,0);
 const citations=await scalar("SELECT public.knowledge_atlas(p_relation=>'citations') v");
 assert.deepEqual(citations.edges,[{source:'12345',target:'12346',weight:1}]);
 const reports=(await scalar("SELECT public.knowledge_paper('12345') v")).related_reports;
 assert.equal(reports[0].pmid,'12346');assert.equal(reports[0].target_relation,'mentioned');
 await assert.rejects(()=>scalar('SELECT public.knowledge_atlas(p_from=>2025,p_to=>2020) v'));
 await db.exec('SET ROLE anon');
 await assert.rejects(()=>scalar('SELECT public.knowledge_atlas() v'),{code:'42501'});
 await assert.rejects(()=>scalar("SELECT public.knowledge_paper('12345') v"),{code:'42501'});
 await db.exec('RESET ROLE;DELETE FROM public.papers WHERE id=991;SET ROLE authenticated');
 await publish('page',{id:cid2,version:'corpus-v1-en',paragraphs:[]});
 assert.equal((await scalar('SELECT public.knowledge_page($1) v',[cid2])).wiki.status,'indexed');
 assert.equal((await scalar('SELECT public.knowledge_search() v')).items.find(c=>c.id===cid2).status,'indexed');
 await assert.rejects(()=>db.query('SELECT * FROM app_private.knowledge_documents'),{code:'42501'});
 await assert.rejects(()=>publish('page',{...page,paragraphs:[{...page.paragraphs[0],sources:[{pmid:'12345',content_hash:'f'.repeat(64),locations:['p-0000000']}]}]}));
 await assert.rejects(()=>publish('page',{...page,paragraphs:[{...page.paragraphs[0],sources:[{pmid:'12345',content_hash:hash,locations:['p-9999999']}]}]}));
 await db.exec("RESET ROLE;UPDATE public.papers SET integrity_status='retracted' WHERE id=1;SET ROLE authenticated");
 assert.equal((await scalar('SELECT public.knowledge_search() v')).items.length,0);
 assert.equal(await scalar('SELECT public.knowledge_page($1) v',[cid]),null);
 await assert.rejects(()=>publish('source',source));
 await db.exec("RESET ROLE;UPDATE public.papers SET integrity_status='current' WHERE id=1;SET ROLE authenticated");
 await publish('source',source);
 assert.equal((await scalar('SELECT public.knowledge_page($1) v',[cid])).wiki.status,'updating');
 assert.deepEqual((await scalar('SELECT public.knowledge_page($1) v',[cid])).wiki.paragraphs,[]);
 await publish('page',page);
 await db.exec("RESET ROLE;UPDATE app_private.local_fulltext_sources SET content_hash=repeat('c',64) WHERE paper_id=1;SET ROLE authenticated");
 assert.equal((await scalar('SELECT public.knowledge_search() v')).indexed_documents,0);
 await assert.rejects(()=>publish('page',page));
 await db.exec('RESET ROLE');
 assert.equal(await scalar('SELECT count(*)::int v FROM app_private.knowledge_science'),0);
 for(const table of ['knowledge_documents','knowledge_concepts','knowledge_memberships','knowledge_pages','knowledge_dependencies','knowledge_science','knowledge_references','knowledge_registries']) {
  assert.equal(await scalar(`SELECT relrowsecurity v FROM pg_class WHERE oid='app_private.${table}'::regclass`),true);
  assert.equal(await scalar(`SELECT has_table_privilege('authenticated','app_private.${table}','SELECT') v`),false);
 }
 console.log('Knowledge DB passed: publication authentication, metadata-only schema, source identity, idempotency, search/graph, RLS, retractions and source invalidation.');
} catch(error) {console.error(error.message,error.code,error.where||error.stack);process.exitCode=1;} finally {await db.close();}
